# Site settings
title: 小树林
email: hizhanghao@tom.com
description: > #小树林
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.buxiaode.cn" # the base hostname & protocol for your site
twitter_username: 
github_username: tiantianxi 

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: xxx
  email: xxx
  
title: 小树林                         #自定义常量

# avatar头像及Favicon
avatar: http://hao.hizhanghao.com/tx.jpg
favicon: http://hao.hizhanghao.com/qrcode.jpg 

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: kramdown                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:
#

# baidu analytics 设置


# disqus 设置
disqus:
  shortname: tiantianxi
